# ----
# Site

title: Memair API
description: Memair API documentation.
url: https://herokuapps.memair.com/api/
api_url: https://herokuapps.memair.com/api/

google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  authentication:
    title: Authentication
    position: 2
  endpoints:
    title: Endpoints
    position: 3
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
