# ----
# Site

title: Memair Docs
description: Memair API documentation.
app_url: https://memair.com/
api_url: https://memair.com/api/

google_analytics_key: UA-28725137-6
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  authentication:
    title: Authentication
    position: 2
  graphql:
    title: GraphQL
    position: 3
  models:
    title: Models
    position: 4
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
  - alpha
  - beta
  - gamma
  - deprecated
  - proposed
